### ISSUE TITLE
Implement jscs with google preset to enforce the javascript style

### ISSUE THREAD

**Issue by chimurai** [incentro/generator-frontend-incubator#1]
- plugin: https://github.com/jscs-dev/node-jscs
- preset: https://github.com/jscs-dev/node-jscs/blob/master/presets/google.json

This also enables auto formatting in editors
- http://blog.jetbrains.com/webstorm/2015/08/maintaining-consistent-code-style/
- http://base2.io/2015/12/30/jscs-intellij-setup/
- https://github.com/SublimeLinter/SublimeLinter-jscs/
- https://github.com/microsoft/vscode-jscs

More info:
http://jscs.info/overview

**Comment by TimoWestland** [comment]
I'm not sure wether we should go for jshint, jscs or eslint as the default javascript linter in the incubator. It might be personal preference and also depending on what kind of project you will be doing with the incubator (e.g. if you are doing a project with React, eslint is the only linter that supports JSX).

This article roughly outlines the pros and cons of the 4 most popular js linters: 
http://www.sitepoint.com/comparison-javascript-linting-tools/

Based on that I see esint being used in most projects I view on github, it claims to have the best es6 support and that it's the most recent of the four, I'm tempted to go for eslint :http://eslint.org/

Webstorm has intergrations for inline linting for all of them.

**Comment by chimurai** [comment]
Agreed, `eslint` should be used for syntax checking.
I opened this issue to implement `jscs` for code-style checking and auto-formatting; to keep the code consistent.

imho, these are two different things.

Think the combination of `jscs` + `eslint` will give the best linting.

**Comment by rburgt** [comment]
@chimurai can you take the lead in this?

**Comment by kaspereden** [comment]
Since there is no action on this for more than 3 months it is assumed not relevant a.t.m.
