### ISSUE TITLE
(re)implement nested build steps naming scheme

### ISSUE THREAD

**Issue by rburgt** [incentro/generator-frontend-incubator#10]
During the conversion from build to compile the naming scheme has also been flattened. The nested naming scheme provided an easy way of referencing which part of the source directory was meant to be build. 

Also the name of the build task should reflect the position of the source file. This way it is easy to find where to fix a possible bug in the build task. No shortnames should be used since these introduce new naming possibilities.

I would like to restore this nested naming scheme since it has been proven to work within large teams and is easy to explain.

Sample:

build:font will become build:asset:font
build:js will become build:asset:javascript

**Comment by chimurai** [comment]
additionally we can introduce the namespaces like `build:angular` and `build:react`, since they might need special treatment during the build process

**Comment by TimoWestland** [comment]
I don't really mind the 'build-up' of the task names, I practically never use them separately anyway. I would opt for renaming compile back to build, since the output folder is also named build this would make more sense in my opinion.

**Comment by chimurai** [comment]
Think you'll loose the semantics if you rename `compile` to `build`. The task names should describe its intended purpose.

https://en.wikipedia.org/wiki/Software_build
https://en.wikipedia.org/wiki/Compiler

Current naming scheme is inspired by: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html 

The whole `build` is series of different tasks. (http://stackoverflow.com/questions/2650168/building-vs-compiling-java)

I wouldn't mind to create a `build` task, which executes a series of granular tasks.

`build` might execute: `clean`, `compile` (and maybe `verify`?)

Doing so, the existing `deploy` task can be simplified from `clean` and `compile` to just `build`

**Comment by kaspereden** [comment]
Does anyone follow up on this? If not I state it to be closed for now
