### ISSUE TITLE
Add friendly introduction to incubator to github-pages

### ISSUE THREAD

**Issue by rburgt** [incentro/generator-frontend-incubator#13]
The incubator website has a poor description which gives no context if you are not familiar with the incubator.
http://incentro.github.io/generator-frontend-incubator/

We need a friendly description to introduce someone with the incubator. 

The website can be updated in the [gh-pages](https://github.com/incentro/generator-frontend-incubator/tree/gh-pages) branch.

**Comment by kaspereden** [comment]
Maybe also make it a little sexier.

**Comment by rburgt** [comment]
@jeroenoomsNL Are you willing to take this task upon you?

**Comment by jeroenoomsNL** [comment]
Yes, this was already on my list ;-)

**Comment by jeroenoomsNL** [comment]
I just updated this Github page. Could you review my "Peppie & Kokkie" English? Thanks! :-)

**Comment by kaspereden** [comment]
I am doubting about this sentence: 

> The Frontend Incubator is a starter kit for building scalable websites and webapplications. The developers of Incentro created this collection of best practices after making the same project structure and build process for each project.

What do you think of this @jeroenoomsNL 
> The Frontend Incubator is a starter kit for building scalable websites and webapplications. The developers of Incentro created this collection of best practices after trying many project structures and build processes.

**Comment by jeroenoomsNL** [comment]
Nice Kasper, much better, I'll change it
