### ISSUE TITLE
Missing dependency: mkdirp

### ISSUE THREAD

**Issue by jenskooij** [incentro/generator-frontend-incubator#15]
When installing, it turns out I'm missing mkdirp module. If you add these to the dependencies it should install this automatically, right?

Anyway here's a screenshot:
![mkdirp](https://cloud.githubusercontent.com/assets/12395129/13846170/80b6c404-ec45-11e5-92ca-e43aa994b99c.png)

**Comment by rburgt** [comment]
yes that should work.

@jenskooij can you add this to the incubator yourself?

**Comment by jenskooij** [comment]
I see now that it's in the devDependencies (although I don't really know what the different is with dependencies/devDependencies).
Should moving / copying the mkdirp module to the regular dependencies fix this, you think?

**Comment by rburgt** [comment]
@kaspereden you encountered this before, can you share your experience on this?

**Comment by kaspereden** [comment]
@rburgt @jenskooij this indeed is a problem devDependencies are only loaded when the project gets checked out and not when you install a package with npm. Thanks for the report! It is now solved will be in the next release
