### ISSUE TITLE
implement node sass-lint

### ISSUE THREAD

**Issue by kaspereden** [incentro/generator-frontend-incubator#2]
https://github.com/sasstools/sass-lint

**Comment by kaspereden** [comment]
Looks like there is only a text reference no real reference...

**Comment by kaspereden** [comment]
I'm doubting whether or not we want to make this an optional feature. What do you guys think?

**Comment by chimurai** [comment]
sass-lint just checks for code style... no real added value imho.

Adding an extra rule in the `.editorconfig` for `scss` should be sufficient.

```
[*.scss]
trim_trailing_whitespace = false
indent_style = space
indent_size = 4
```

I prefer implementing [`csslint`](https://www.npmjs.com/package/csslint), which add real css syntax checking.

**Comment by rsistermans** [comment]
Optional, yes, but I would advise using sass/scss-lint. Languages like SASS make it too easy for developers to go overboard.

Two useful examples:
- Setting a nesting limit so your selectors do not become overly abstract and hard-to-read. This often results in creating lots of nested selector trees doing almost the same.
- Checking for selector duplication and merge opportunities. Helps developers organize code.

Linters should be strict enough that a developer treats every warning as a must-fix. If warnings end up not being fixed the check should be removed from the linter.

A general editorconfig could/should check things like indentation.

I'm not sure what benefits csslint has, but I'm sure they can live together.

**Comment by kaspereden** [comment]
I've made sass-lint an optional feature. Default it is turned on because previously mentioned reasons. I've made some assumptions in the sass-lint settings, we will see later what works and what doesn't.
