### ISSUE TITLE
ascii art is missing

### ISSUE THREAD

**Issue by 127001** [incentro/generator-frontend-incubator#29]
The incubater could really use some ascii art during the 'yo frontend-incubator'-phase.

**Comment by 127001** [comment]
![helmet](https://cloud.githubusercontent.com/assets/149222/15007450/5ca607c8-11d9-11e6-84b4-5f4690d39f47.png)
[helmet.txt](https://github.com/incentro/generator-frontend-incubator/files/248286/helmet.txt)

**Comment by kaspereden** [comment]
:+1:

**Comment by kaspereden** [comment]
@127001 feel free to implement :)
