### ISSUE TITLE
when running the build of the incubator on linux

### ISSUE THREAD

**Issue by rjvw** [incentro/generator-frontend-incubator#40]
There is an issue when with one of your plugins. See logs below.

[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m frontend-incubator-kss-template@2.0.2 postinstall: `gulp`
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Exit status 1
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Failed at the frontend-incubator-kss-template@2.0.2 postinstall script 'gulp'.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m This is most likely a problem with the frontend-incubator-kss-template package,
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m not with npm itself.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Tell the author that this fails on your system:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     gulp
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m You can get information on how to open an issue for this project with:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm bugs frontend-incubator-kss-template
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Or if that isn't available, you can get their info via:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm owner ls frontend-incubator-kss-template
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m There is likely additional logging output above.

**Comment by kaspereden** [comment]
is there a difference in node versions?
