### ISSUE TITLE
Swig block for setting page title's is not working properly

### ISSUE THREAD

**Issue by TimoWestland** [incentro/generator-frontend-incubator#7]
The current implementation setting page titles in the document head in base.html using a swig block is not working properly.
`{% block pageTitle %}Page title{% endblock%}`

This can be fixed by using a swig variable instead of a block like this:

In base.html in the head:

`{% set pageTitle = pageTitle|default('') %}`
`<title>{{pageTitle}}</title>`

And then you can set a page title on every page:

`{% set pageTitle = 'Autoverzekering' %}`

In my opinion it does also make more sense to use variables for this since we're not injecting a code block but a string.

**Comment by kaspereden** [comment]
:+1:

**Comment by rburgt** [comment]
I will create a pull request for this

**Comment by kaspereden** [comment]
Merged
