### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by PizzaPete** [incentro/generator-frontend-incubator#9]
It would be nice to automatically check whether the build process fails or succeeds using CodeShip.

**Comment by kaspereden** [comment]
Do you want this for this project or for the generated projects?

**Comment by PizzaPete** [comment]
There should be tests inside the project that must be run with npm test to see if the generated project is being generated as it should.
These tests should be executed with CodeShip or Travis. Example: https://travis-ci.org/PizzaPete/generator-ionic-incubator/

**Comment by rburgt** [comment]
@PizzaPete Can you create a pull request for this? I would love to have a baseline for these kind of implementations.

Keep in mind that not every project needs this as a default implementation, can you make it optional?

**Comment by kaspereden** [comment]
@PizzaPete also look at issue #4 we can probably execute those tests with codeship? 

@rburgt I think he means tests for the generator itself not the generated projects

**Comment by PizzaPete** [comment]
You must have a subscribed (payed account) organisation to use builds on Codeship as a company.
I'm going to look into Travis CI now.

**Comment by kaspereden** [comment]
We do have a subscribed BAMBOO account, isn't that able to do the exact same thing?

**Comment by PizzaPete** [comment]
Are the results of the Bamboo build open to everyone?

**Comment by kaspereden** [comment]
will check

**Comment by kaspereden** [comment]
Nope, doesn't work :(

**Comment by kaspereden** [comment]
@PizzaPete please make a pull request once its done :)

**Comment by PizzaPete** [comment]
I've implemented a .travis.yml file and updated the README.md in: commit: #19 
Although the build fails.

**Comment by BartWaardenburg** [comment]
It seems to fail on older versions of node on the es6 notation in the gulp script. I think we should remove those versions from the Travis config.

**Comment by kaspereden** [comment]
looks like its fixed, i'll close this issue for now
